// (c) Gravicity · BSL 1.1 · soma.gravicity.ai
// Built by Curtis Mercier
var D=Object.defineProperty;var c=(l,y)=>D(l,"name",{value:y,configurable:!0});import{existsSync as f,readFileSync as h,writeFileSync as $,mkdirSync as x}from"fs";import{join as C,dirname as M}from"path";import{findSomaDir as O,loadSettings as E,getSomaChain as F,resolveSomaPath as G}from"../core/index.js";function P(l){let y=null,v=null,N=!1;l.on("session_start",async()=>{let s=O();if(!s)return;let e=F(),t=E(e);y=s.path,v=G(s.path,"sessions",t),j();let r=t?.scratch?.autoInject??!1;if(!N&&r){N=!0;let o=m();if(o.length>0){let i=`## \u{1F4DD} Scratch Notes

You have ${o.length} active note(s) from previous sessions. Consider how they apply:

`+o.map(n=>`- ${n.text} *(session: ${n.sessionId}, ${n.date})*`).join(`
`);setTimeout(()=>{l.sendUserMessage(i,{deliverAs:"followUp"})},500)}}});function p(){return v?C(v,"scratchpad.md"):null}c(p,"getScratchPath");function U(s){let e=M(s);f(e)||x(e,{recursive:!0})}c(U,"ensureDir");function w(){let t=globalThis.t?.get("session:id")?.();return t?t.slice(-6):"??????"}c(w,"getSessionId");function W(){return new Date().toISOString().split("T")[0]}c(W,"today");function T(){return new Date().toLocaleTimeString("en-US",{hour12:!1,hour:"2-digit",minute:"2-digit"})}c(T,"timestamp");function S(s){let e=[],t="",r=0;for(let o of s.split(`
`)){let i=o.match(/^## (\d{4}-\d{2}-\d{2})/);if(i){t=i[1];continue}let n=o.match(/^- \[(\d{2}:\d{2})\] (.+?)(?:\s*<!--\s*sid:(\w+)(?:\s+status:(\w+))?\s*-->)?$/);if(n){r++;let[,a,u,g,A]=n,d=u;d.startsWith("~~")&&d.endsWith("~~")&&(d=d.slice(2,-2)),d.startsWith("*")&&d.endsWith("*")&&!d.startsWith("**")&&(d=d.slice(1,-1)),e.push({index:r,time:a,text:d,sessionId:g||"??????",status:A||"active",date:t,raw:o})}}return e}c(S,"parseNotes");function m(){let s=p();if(!s||!f(s))return[];let e=h(s,"utf-8");return S(e).filter(t=>t.status==="active")}c(m,"getActiveNotes");function b(s,e,t){let r=T();switch(e){case"done":return`- [${r}] ~~${s}~~ <!-- sid:${t} status:done -->`;case"parked":return`- [${r}] *${s}* <!-- sid:${t} status:parked -->`;default:return`- [${r}] ${s} <!-- sid:${t} -->`}}c(b,"formatNote");function I(s,e){U(s);let t=f(s)?h(s,"utf-8"):"",r=`## ${W()}`;if(t.includes(r)){let o=t.indexOf(r),i=t.indexOf(`
`,o),n=t.indexOf(`
## `,i+1),a=n===-1?t.length:n,u=t.slice(0,a).trimEnd()+`
`+e+`
`+(n!==-1?`
`+t.slice(n):"");$(s,u)}else{let o=`${r}

${e}
`;$(s,t?o+`
`+t:o)}}c(I,"appendWithDate");function k(s,e){let t=p();if(!t||!f(t))return{success:!1};let r=h(t,"utf-8"),i=S(r).find(g=>g.index===s);if(!i)return{success:!1};let n,a=i.sessionId;switch(e){case"done":n=`- [${i.time}] ~~${i.text}~~ <!-- sid:${a} status:done -->`;break;case"parked":n=`- [${i.time}] *${i.text}* <!-- sid:${a} status:parked -->`;break;case"active":n=`- [${i.time}] ${i.text} <!-- sid:${a} -->`;break}let u=r.replace(i.raw,n);return $(t,u),{success:!0,note:{...i,status:e}}}c(k,"updateNoteStatus");function j(){let s=globalThis.t;s&&(s.provide("scratch:read",()=>{let e=p();return!e||!f(e)?"":h(e,"utf-8")},{provider:"soma-scratch",description:"Get full scratchpad content as string"}),s.provide("scratch:append",e=>{let t=p();if(!t)return!1;let r=w(),o=b(e,"active",r);return I(t,o),!0},{provider:"soma-scratch",description:"Programmatically append a note (from any extension)"}),s.provide("scratch:active",()=>m(),{provider:"soma-scratch",description:"Get array of active (non-done, non-parked) notes"}),s.provide("scratch:count",()=>m().length,{provider:"soma-scratch",description:"Get count of active notes (for statusline)"}))}c(j,"provideToRouter"),l.registerCommand("scratch",{description:"Quick notes \u2014 append to scratchpad with session tracking",getArgumentCompletions:c(s=>["read","clear","done","park","activate","notes"].filter(t=>t.startsWith(s)).map(t=>({value:t,label:t})),"getArgumentCompletions"),handler:c(async(s,e)=>{let t=p();if(!t){e.ui.notify("No .soma/ found. Run /soma init first.","error");return}let r=s.trim();if(r==="read"){if(!f(t)){e.ui.notify("\u{1F4DD} Scratchpad is empty.","info");return}let n=h(t,"utf-8");l.sendUserMessage(`[Scratchpad \u2014 ${t}]

${n}`,{deliverAs:"followUp"});return}if(r==="clear"){f(t)?($(t,""),e.ui.notify("\u{1F5D1}\uFE0F Scratchpad cleared.","info")):e.ui.notify("\u{1F4DD} Scratchpad already empty.","info");return}if(r==="notes"){if(!f(t)){e.ui.notify("\u{1F4DD} Scratchpad is empty.","info");return}let n=S(h(t,"utf-8"));if(!n.length){e.ui.notify("\u{1F4DD} No notes.","info");return}let a=n.map(u=>`  ${u.status==="done"?"\u2705":u.status==="parked"?"\u23F8\uFE0F":"\u{1F4DD}"} #${u.index} [${u.time}] ${u.text} (${u.sessionId})`);e.ui.notify(`\u{1F4CB} Notes:
${a.join(`
`)}`,"info");return}if(r.startsWith("done")){let n=parseInt(r.slice(4).trim());if(isNaN(n)){e.ui.notify("Usage: /scratch done <note-number>. Use /scratch notes to see numbers.","info");return}let a=k(n,"done");a.success?e.ui.notify(`\u2705 Note #${n} done: ${a.note?.text?.slice(0,60)}`,"info"):e.ui.notify(`\u274C Note #${n} not found. Use /scratch notes.`,"error");return}if(r.startsWith("park")){let n=parseInt(r.slice(4).trim());if(isNaN(n)){e.ui.notify("Usage: /scratch park <note-number>. Use /scratch notes to see numbers.","info");return}let a=k(n,"parked");a.success?e.ui.notify(`\u23F8\uFE0F Note #${n} parked: ${a.note?.text?.slice(0,60)}`,"info"):e.ui.notify(`\u274C Note #${n} not found. Use /scratch notes.`,"error");return}if(r.startsWith("activate")){let n=parseInt(r.slice(8).trim());if(isNaN(n)){e.ui.notify("Usage: /scratch activate <note-number>.","info");return}let a=k(n,"active");a.success?e.ui.notify(`\u{1F4DD} Note #${n} reactivated: ${a.note?.text?.slice(0,60)}`,"info"):e.ui.notify(`\u274C Note #${n} not found.`,"error");return}if(!r){let n=m().length;e.ui.notify(`\u{1F4DD} Scratchpad (${n} active notes)

  /scratch <note>       \u2014 append a note (agent won't see it)
  /scratch read         \u2014 show scratchpad to agent
  /scratch notes        \u2014 numbered list with status
  /scratch done <n>     \u2014 mark note #n as completed
  /scratch park <n>     \u2014 park note (kept, not injected)
  /scratch activate <n> \u2014 reactivate a parked/done note
  /scratch clear        \u2014 empty the scratchpad`,"info");return}let o=w(),i=b(r,"active",o);try{I(t,i),e.ui.notify(`\u{1F4DD} Noted. (sid:${o})`,"info")}catch(n){e.ui.notify(`\u274C Failed to write: ${n?.message?.slice(0,80)}`,"error")}},"handler")})}c(P,"somaScratch");export{P as default};
